#!/bin/sh

# Defauls
_key_out=/root/geli/master.key


encryption::init(){

    encryption::init::usage() { 
        echo "Usage: $0 encrypt init -o </path/to/geli.key> (Default: $_key_out)" 1>&2
        exit 1 
    }

    while getopts ":o:h" opt
    do
        case $opt in
            o ) _key_out=$OPTARG ;;
            h ) encryption::init::usage ;;
            \? ) echo "Invalid option: -$OPTARG. Use -h for usage" >&2
            exit ;;
            : ) echo "Option -$OPTARG requires an argument" >&2
            exit ;;
        esac
    done

    # Pre-checks
    if [ ! $_key_out ]; then
        encryption::init::usage
        exit 1
    fi

    if [ -f $_key_out ]
    then
        echo "File already exists. Aborting."
        exit 1
    fi

    util::confirm "Do you want to create a new GELI master key stored in $_key_out?" || exit 0

    mkdir -p "${_key_out%/*}"
    touch ${_key_out}
    dd if=/dev/random of=${_key_out} bs=64 count=1 > /dev/null 2>&1
    [ $? -eq 0 ] || util::err "Could not generate key ${_key_out}"
    chmod 400 ${_key_out}
    chmod 700 "${_key_out%/*}"
    echo

    md5 $_key_out
    echo
    echo "NOTICE: Store $_key_out in a safe location! Without it your data is lost! (unless you're Dade Murphy)"

}


encryption::disk(){
    # Defaults
    _master_key=$_key_out

    encryption::disk::usage() {
        echo "Usage: $0 encrypt disk -k </path/to/geli/master.key> /dev/diskN1 [/dev/diskN2 /dev/diskN3...]" 1>&2
        echo "    Default key location: $_key_out" 1>&2
        exit 1 
    }

    while getopts ":d:k:h" opt
    do
        case $opt in
            k ) _master_key=$OPTARG ;;
            h ) encryption::disk::usage ;;
            \? ) echo "Invalid option: -$OPTARG. Use -h for usage" >&2
            exit ;;
            : ) echo "Option -$OPTARG requires an argument" >&2
            exit ;;
        esac
    done

    shift $((OPTIND - 1))
    _devlist=$@

    # Pre-checks
    if [ ! $_master_key ]; then
        encryption::disk::usage
        exit 1
    fi

    if [ ! -f $_master_key ]
    then
        util::err "No such file: $_master_key"
    fi

    for _disk in ${_devlist}; do
        if [ ! $_disk ]; then
            util::err "No disk specified"
        fi

        if [ ! -e $_disk ]
        then
            util::err "No such device: $_disk"
        fi

        if [ ! $(echo $_disk | grep dev) ]; then
            util::err "Enter full path to your disk"
        fi
    done

    util::confirm "GELI encrypt $_devlist?" || exit 0
    
    stty -echo
    printf "Enter passphrase: "
    read pass
    printf "\n"
    printf "Reenter passphrase: "
    read pass2
    stty echo
    echo

    [ ! $pass == $pass2 ] && util::err "Passwords must match"

    for _disk in ${_devlist}; do
        echo -n $pass | geli init -e AES-XTS -s 4096 -l 256 -B none -J - -K $_master_key $_disk > /dev/null 2>&1
        [ $? -eq 0 ] || util::err "Could not init geli on $_disk"
    done
}


encryption::attach(){
    # Defaults
    _master_key=$_key_out

    encryption::attach::usage() {
        echo "Usage: $0 encrypt attach -k </path/to/geli/master.key> /dev/diskN1 [/dev/diskN2 /dev/diskN3...]" 1>&2
        exit 1 
    }

    while getopts ":d:k:h" opt
    do
        case $opt in
            d ) _disk=$OPTARG ;; # Emenate
            k ) _master_key=$OPTARG ;;
            h ) encryption::attach::usage;;
            \? ) echo "Invalid option: -$OPTARG. Use -h for usage" >&2
            exit ;;
            : ) echo "Option -$OPTARG requires an argument" >&2
            exit ;;
        esac
    done

    shift $((OPTIND - 1))
    _devlist=$@

    # Pre-checks
    if [ ! $_master_key ]; then
        encryption::attach::usage
        exit 1
    fi

    if [ ! -f $_master_key ]
    then
        util::err "No such file: $_master_key"
        exit 1
    fi

    for _disk in ${_devlist}; do 
        if [ ! $_disk ]; then
            encryption::attach::usage
            exit 1
        fi

        if [ ! -e $_disk ]
        then
            echo "No such device: $_disk"
            encryption::attach::usage
            exit 1
        fi

        if [ ! $(echo $_disk | grep dev) ]; then
            echo "Enter full path to your disk"
            exit 1
        fi
    done

    stty -echo
    printf "Enter passphrase: "
    read pass
    stty echo
    echo

    for _disk in ${_devlist}; do 
        echo -n "$pass" | geli attach -j - -k "$_master_key" "$_disk" > /dev/null 2>&1
        [ $? -eq 0 ] || util::err "Could not attach encrypted device ${_disk}"
        if [ -e $_disk.eli ]; then
            echo "Encrypted devive available: $_disk.eli"
        fi
    done
}
