#!/bin/sh

util::version(){
    echo "fbsd-nas: FreeBSD ZFS and disk management v${VERSION}"
}

util::usage(){
    util::version
    cat << EOT
Usage: nas ...
    version
    help
    usage

    disk list
    disk wipe /dev/diskN1 [/dev/diskN2 /dev/diskN3...]
    disk partition [-s <data size>] [-a <4096|512>] /dev/diskN1 [/dev/diskN2 /dev/diskN3...]
    disk label [-s][-u][-c] /dev/diskN1pX [/dev/diskN2pX /dev/diskN3pX...]
    disk dummyboot -d </dev/disk>
    disk hotswap /dev/diskN
    encrypt init -o /path/to/master.key
    encrypt disk -k /path/to/master.key /dev/diskN1 [/dev/diskN2 /dev/diskN3...]
    encrypt attach -k /path/to/master.key /dev/diskN1
    zpool list
    zpool create -n <name> [-t <type>] -d <"[type] /dev/disk1 [diskN ...]">
    zfs list
    zfs create [-r refquota] [-q quota]

EOT
    exit 1
}

util::err(){
    echo "${0}: ERROR: $1" >&2
    exit 1
}

util::err_inline(){
    echo "  ! $1"
    exit 1
}

util::warn(){
    echo "${0}: WARNING: $1" >&2
}

util::info(){
    echo "${0}: INFO: $1" >&2
}

util::confirm(){
    local _msg="$1"
    local _resp

    while read -p "${_msg} (y/n)? " _resp; do
        case "${_resp}" in
            y*) return 0 ;;
            n*) return 1 ;;
        esac
    done
}
